$grammar = [
  Rule.new('S', ['S', '+', 'A']),
  Rule.new('S', ['S', '-', 'A']),
  Rule.new('S', ['A']),
  Rule.new('A', ['A', '*', 'B']),
  Rule.new('A', ['A', '/', 'B']),
  Rule.new('A', ['B']),
  Rule.new('B', ['-', 'B']),
  Rule.new('B', ['C']),
  Rule.new('C', ['D', '^', 'B']),
  Rule.new('C', ['D']),
  Rule.new('D', ['(', 'S', ')']),
  Rule.new('D', ['N']),
  Rule.new('N', ['O', 'N']),
  Rule.new('N', ['O']),
  Rule.new('O', ['0']),
  Rule.new('O', ['1']),
  Rule.new('O', ['2']),
  Rule.new('O', ['3']),
  Rule.new('O', ['4']),
  Rule.new('O', ['5']),
  Rule.new('O', ['6']),
  Rule.new('O', ['7']),
  Rule.new('O', ['8']),
  Rule.new('O', ['9']),
]
